<a href="https://colab.research.google.com/github/shubhamvermaaws-spec/My-first-ai-machine-learning-project/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch fundamentals

Resource Notebook - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Introduction to Tensors


### Creating Tensors

PyTorch tensors are created using 'torch.tensor()' = https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR With 3 Dimension
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

In [18]:
# TENSOR with 4 dimension
TENSOR = torch.tensor([[[[1,2,3],[3,6,9],[2,4,5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [19]:
TENSOR.ndim

4

In [20]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [21]:
TENSOR[0]

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR[0][0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
TENSOR[0][0][0]

tensor([1, 2, 3])

In [24]:
# TENSOR with 5 dimension
TENSOR = torch.tensor([[[[[1,2,3],[3,6,9],[2,4,5]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [3, 6, 9],
           [2, 4, 5]]]]])

In [25]:
TENSOR.ndim

5

In [26]:
TENSOR.shape

torch.Size([1, 1, 1, 3, 3])

In [27]:
TENSOR[0]

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [28]:
TENSOR[0][0]

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [29]:
TENSOR[0][0][0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [30]:
TENSOR[0][0][0][0]

tensor([1, 2, 3])

Here Each Bracket represent the dimension you keep increasing the bracket your dimension also get increasing.

### Random tensors

why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers

torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [31]:
# create a random tensors of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2311, 0.5474, 0.0186, 0.3886],
        [0.4237, 0.8003, 0.8794, 0.7024],
        [0.6802, 0.8619, 0.2912, 0.7095]])

In [32]:
random_tensor.ndim

2

In [33]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width and colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [34]:
# create my own randon tensor
my_random_tensor = torch.rand(50, 50, 10)
my_random_tensor.shape, my_random_tensor.ndim, my_random_tensor

(torch.Size([50, 50, 10]),
 3,
 tensor([[[0.2579, 0.2681, 0.3074,  ..., 0.8568, 0.9628, 0.0330],
          [0.7844, 0.6628, 0.4539,  ..., 0.6955, 0.2279, 0.6232],
          [0.5803, 0.8463, 0.9921,  ..., 0.8947, 0.0883, 0.5916],
          ...,
          [0.3177, 0.1604, 0.4931,  ..., 0.0719, 0.3133, 0.2255],
          [0.1703, 0.8488, 0.6251,  ..., 0.4586, 0.7215, 0.6798],
          [0.2799, 0.9365, 0.4694,  ..., 0.6574, 0.0656, 0.2418]],
 
         [[0.3947, 0.5607, 0.2163,  ..., 0.0634, 0.7442, 0.3730],
          [0.9947, 0.8766, 0.2628,  ..., 0.8981, 0.7083, 0.2251],
          [0.3078, 0.1836, 0.0109,  ..., 0.2627, 0.7257, 0.5644],
          ...,
          [0.5792, 0.4480, 0.2214,  ..., 0.7061, 0.7051, 0.6911],
          [0.4264, 0.8125, 0.5838,  ..., 0.2517, 0.5101, 0.7260],
          [0.0690, 0.2090, 0.3559,  ..., 0.7088, 0.5802, 0.4617]],
 
         [[0.9428, 0.2332, 0.1451,  ..., 0.1163, 0.5145, 0.5149],
          [0.9084, 0.8468, 0.6916,  ..., 0.0760, 0.7702, 0.8895],
         

### Zeroes and Ones

In [35]:
# create a tensor of all zeroes
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [39]:
random_tensor.dtype

torch.float32

### Creating a rang of tensors and tensors-like

In [40]:
# use torch.range()
torch.range(0, 10)

/tmp/ipython-input-4106555132.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
# use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data types
**Note:** tensor datatypes is one of the 3 big errors you will run into with pytorch and deep learning


1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device



In [45]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [46]:
float_32_tensor.dtype

torch.float32

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
Tensor Attributes


1.   To get datatype from a tensor, can use 'tensor.dtype'.
2.   To get shape of tensor, can use 'tensor.shape'
3.   To get device from a tensor, can use 'tensor.device'.



In [49]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4824, 0.2380, 0.5922, 0.9549],
        [0.9267, 0.4061, 0.4261, 0.5077],
        [0.4678, 0.3110, 0.9412, 0.4700]])

In [50]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4824, 0.2380, 0.5922, 0.9549],
        [0.9267, 0.4061, 0.4261, 0.5077],
        [0.4678, 0.3110, 0.9412, 0.4700]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [51]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [52]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [53]:
# Substract by 10
tensor-10

tensor([-9, -8, -7])

In [54]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [55]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two Main Ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix Multiplication (dot product)

More infromation on multiplying matrices- https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are Two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* (3, 2) @ (3, 2) this wont work
* (2, 3) @ (3, 2) this will work
* (3, 2) @ (2, 3) this will work

2. The resulting matrix has the shape of the **outer dimension**:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [56]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.01 ms, sys: 0 ns, total: 1.01 ms
Wall time: 1.22 ms


In [59]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 31 µs, sys: 4 µs, total: 35 µs
Wall time: 38.1 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [60]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [61]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[1.0474, 0.6148],
        [1.8224, 1.0469]])

In [62]:
# shapes for matrix multiplications
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matrix multiplication)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [63]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **torch.transpose**

A **transpose** switches the axes or dimension of given tensor

In [64]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [65]:
tensor_B.shape

torch.Size([3, 2])

In [66]:
tensor_B.T.shape

torch.Size([2, 3])

In [67]:
# The matrix multiplications operations works when tensor_b is
print(f"original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"new shapes: tensor_A = {tensor_A.shape} (same Shape as above ), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T).shape

original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shapes: tensor_A = torch.Size([3, 2]) (same Shape as above ), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


torch.Size([3, 3])

In [68]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [69]:
tensor_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

## Finding the min, max, mean, sum, etc(tensor aggregation)

In [70]:
# create a tensor
x= torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [71]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [72]:
# Find the maz
torch.max(x), x.max()

(tensor(90), tensor(90))

In [73]:
# Find the mean- note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [74]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [75]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [76]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [77]:
# Find the position in tensor that has the minimum value with argmin() -> returns the index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [78]:
# Find the position in tensor that has the minimum value with argmax() -> return the index position of target tensor where the maximum value accours
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [79]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [80]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [81]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [82]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0]= 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [83]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [84]:
x_cat = torch.cat([x, x, x, x], dim=0)
x_cat

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [85]:
# torch.squeeze() - removes all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [86]:
x_reshaped.shape

torch.Size([1, 9])

In [87]:
 x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
x_reshaped.shape

torch.Size([1, 9])

In [89]:
x_reshaped.squeeze().shape

torch.Size([9])

In [90]:
# torch.unsqueeze() - adds a single dimension to a target tensor at specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [91]:
# torch.permute() - rearranges the dimension of a target tensor in a specific order
x_permuted = torch.randn(2,3,5)
x_permuted.size()

torch.permute(x_permuted, (1, 2, 0)).size()

torch.Size([3, 5, 2])

In [92]:
x_original = torch.rand(size = (224, 224, 3))
x_original.shape

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_permuted.shape
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [93]:
x_original[0, 0, 0] = 280699

In [94]:
x_original

tensor([[[2.8070e+05, 1.2300e-01, 4.2028e-01],
         [7.8905e-01, 8.9043e-02, 5.1024e-01],
         [4.0992e-01, 5.4815e-01, 2.8565e-01],
         ...,
         [6.8794e-01, 5.2149e-01, 1.3625e-01],
         [5.9987e-01, 7.6474e-01, 9.4818e-01],
         [3.7292e-01, 9.5915e-03, 6.3526e-01]],

        [[8.9668e-01, 6.0293e-01, 3.6321e-01],
         [8.7906e-01, 9.5257e-01, 8.9984e-01],
         [9.8173e-01, 6.6418e-01, 4.4865e-02],
         ...,
         [3.7900e-01, 7.9391e-01, 2.3376e-01],
         [2.6838e-01, 9.6006e-01, 7.4464e-01],
         [7.8275e-01, 8.6263e-01, 5.3873e-01]],

        [[5.9577e-01, 7.6007e-01, 6.7371e-01],
         [5.8713e-02, 1.8102e-01, 6.8167e-01],
         [3.9509e-01, 9.3416e-01, 6.9857e-01],
         ...,
         [2.3719e-01, 8.9177e-01, 5.9327e-02],
         [2.2491e-01, 4.0421e-01, 5.6918e-01],
         [8.7185e-01, 2.9545e-01, 8.7434e-01]],

        ...,

        [[8.9692e-01, 3.9666e-01, 5.6832e-01],
         [3.4326e-01, 5.7754e-01, 1.7805e-01]

In [95]:
x_permuted

tensor([[[2.8070e+05, 7.8905e-01, 4.0992e-01,  ..., 6.8794e-01,
          5.9987e-01, 3.7292e-01],
         [8.9668e-01, 8.7906e-01, 9.8173e-01,  ..., 3.7900e-01,
          2.6838e-01, 7.8275e-01],
         [5.9577e-01, 5.8713e-02, 3.9509e-01,  ..., 2.3719e-01,
          2.2491e-01, 8.7185e-01],
         ...,
         [8.9692e-01, 3.4326e-01, 2.8009e-01,  ..., 9.8761e-02,
          6.8415e-01, 2.9373e-01],
         [1.3561e-01, 4.2580e-01, 3.8647e-01,  ..., 7.8001e-01,
          8.1465e-01, 8.4950e-01],
         [8.4055e-01, 7.3960e-01, 8.8116e-01,  ..., 8.0376e-01,
          9.0913e-01, 9.7037e-01]],

        [[1.2300e-01, 8.9043e-02, 5.4815e-01,  ..., 5.2149e-01,
          7.6474e-01, 9.5915e-03],
         [6.0293e-01, 9.5257e-01, 6.6418e-01,  ..., 7.9391e-01,
          9.6006e-01, 8.6263e-01],
         [7.6007e-01, 1.8102e-01, 9.3416e-01,  ..., 8.9177e-01,
          4.0421e-01, 2.9545e-01],
         ...,
         [3.9666e-01, 5.7754e-01, 1.6323e-03,  ..., 4.1423e-01,
          6.819

In [96]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(280699.), tensor(280699.))

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy

In [97]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [98]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [99]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [100]:
# Let's index on the third dimension (last dimension)
x[0][0][0]

tensor(1)

In [101]:
x[0][1][1]

tensor(5)

In [102]:
x[0][2][2]

tensor(9)

In [103]:
# You can also use ':' to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [104]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [105]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [106]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [107]:
# Index on x to return 9 and 3, 6, 9
x[:, 2, 2]
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors and numpy

NumPy is a popular scientific Python numerical computing library
and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [108]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # when converting to tensor from numpy, tensor reflects numpy's default data type of float62 unless sepcified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [109]:
array.dtype

dtype('float64')

In [110]:
tensor.dtype

torch.float32

In [111]:
# Change the value of array, what will this do to tensor ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [112]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [113]:
# Change the tensor what happens to numpy tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
Start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [114]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2599, 0.4165, 0.0032, 0.8689],
        [0.5133, 0.3831, 0.4992, 0.9439],
        [0.1456, 0.7803, 0.7436, 0.5694]])
tensor([[0.3091, 0.9874, 0.1437, 0.8100],
        [0.8549, 0.9850, 0.7143, 0.9195],
        [0.3351, 0.6501, 0.1164, 0.2425]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [115]:
# Let's make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the GPUs and making faster computations

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + pytorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - take a little bit of setup and required investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure

### 2. Check for GPU access with PyTorch

In [116]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [117]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [118]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU

The reason we want our tensors/models on GPU is because using a GPU results in faster computations

In [119]:
# create a tensor on CPU
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [120]:
# Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the cpu

In [121]:
# if tensor is on gpu cant transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [122]:
tensor.cpu()

tensor([1, 2, 3])

In [123]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
## Exercises and Extra-curriculum