<a href="https://colab.research.google.com/github/shubhamvermaaws-spec/My-first-ai-machine-learning-project/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor


tensor([[6.7990e-01, 8.9692e-01, 5.3934e-01, 8.8202e-01, 6.7215e-01, 8.4179e-01,
         7.3052e-01],
        [3.3793e-01, 3.1217e-01, 2.8519e-01, 6.4936e-01, 6.5297e-01, 3.0949e-02,
         8.8563e-01],
        [6.1980e-01, 3.3118e-01, 7.4486e-01, 4.8662e-01, 1.7248e-01, 9.2718e-01,
         8.4928e-01],
        [3.7779e-02, 3.4468e-01, 8.4676e-01, 3.2057e-02, 9.1386e-01, 2.9259e-01,
         4.3387e-01],
        [2.7850e-01, 4.3854e-02, 1.1194e-01, 2.9239e-01, 4.1553e-01, 5.0605e-01,
         2.0732e-01],
        [1.1055e-01, 7.0844e-01, 8.6596e-01, 1.3556e-01, 5.6158e-01, 7.1070e-01,
         9.6224e-01],
        [9.5834e-01, 5.6297e-01, 3.4557e-01, 2.9032e-01, 3.8385e-05, 6.3399e-01,
         5.4549e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)
random_tensor_2 = random_tensor_2.T
random_tensor_2.shape

# Perform matrix multiplication
result_tensor = torch.matmul(random_tensor, random_tensor_2)
result_tensor, result_tensor.shape


(tensor([[2.7109],
         [1.3633],
         [1.8034],
         [1.5028],
         [1.0185],
         [1.8242],
         [1.7726]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
random_tensor_3 = torch.rand(7, 7)
random_tensor_4 = torch.rand(1, 7)
random_tensor_4 = random_tensor_4.T


# Matrix multiply tensors
result_tensor_2 = torch.matmul(random_tensor_3, random_tensor_4)
result_tensor_2, result_tensor_2.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)


# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
random_tensor_5 = torch.rand(2, 3).to("cuda")
random_tensor_6 = torch.rand(2, 3).to("cuda")
random_tensor_5, random_tensor_6


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
random_tensor_5 = random_tensor_5.T
result_tensor_3 = torch.matmul(random_tensor_5, random_tensor_6)
result_tensor_3, result_tensor_3.shape



(tensor([[0.1230, 0.3009, 0.2260],
         [0.0401, 0.2338, 0.3036],
         [0.2457, 0.6707, 0.5696]], device='cuda:0'),
 torch.Size([3, 3]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
tensor_max = torch.max(result_tensor_3)

# Find min
tensor_min = torch.min(result_tensor_3)
tensor_min, tensor_max


(tensor(0.0401, device='cuda:0'), tensor(0.6707, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
max_index = torch.argmax(result_tensor_3)


# Find arg min
min_index = torch.argmin(result_tensor_3)
max_index, min_index


(tensor(7, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random_tensor_7 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor = torch.squeeze(random_tensor_7)


# Print out tensors and their shapes
random_tensor_7, random_tensor_7.shape, squeezed_tensor, squeezed_tensor.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))